#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXrandr
Version  : 1.5.1
Release  : 13
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.1.tar.gz
Summary  : X RandR Library
Group    : Development/Tools
License  : HPND
Requires: libXrandr-lib
Requires: libXrandr-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32randrproto)
BuildRequires : pkgconfig(32renderproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xrender)
BuildRequires : pkgconfig(randrproto)
BuildRequires : pkgconfig(renderproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)

%description
libXrandr - X Resize, Rotate and Reflection extension library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXrandr package.
Group: Development
Requires: libXrandr-lib
Provides: libXrandr-devel

%description dev
dev components for the libXrandr package.


%package dev32
Summary: dev32 components for the libXrandr package.
Group: Default
Requires: libXrandr-lib32

%description dev32
dev32 components for the libXrandr package.


%package doc
Summary: doc components for the libXrandr package.
Group: Documentation

%description doc
doc components for the libXrandr package.


%package lib
Summary: lib components for the libXrandr package.
Group: Libraries

%description lib
lib components for the libXrandr package.


%package lib32
Summary: lib32 components for the libXrandr package.
Group: Default

%description lib32
lib32 components for the libXrandr package.


%prep
%setup -q -n libXrandr-1.5.1
pushd ..
cp -a libXrandr-1.5.1 build32
popd

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
%configure --disable-static  --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do mv $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xrandr.h
/usr/lib64/libXrandr.so
/usr/lib64/pkgconfig/xrandr.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXrandr.so
/usr/lib32/pkgconfig/32xrandr.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXrandr.so.2
/usr/lib64/libXrandr.so.2.2.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXrandr.so.2
/usr/lib32/libXrandr.so.2.2.0
