#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXrandr
Version  : 1.5.1
Release  : 8
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.1.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXrandr-1.5.1.tar.gz
Summary  : X RandR Library
Group    : Development/Tools
License  : HPND
Requires: libXrandr-lib
Requires: libXrandr-doc
BuildRequires : pkgconfig(randrproto)
BuildRequires : pkgconfig(renderproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)

%description
libXrandr - X Resize, Rotate and Reflection extension library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXrandr package.
Group: Development
Requires: libXrandr-lib
Provides: libXrandr-devel

%description dev
dev components for the libXrandr package.


%package doc
Summary: doc components for the libXrandr package.
Group: Documentation

%description doc
doc components for the libXrandr package.


%package lib
Summary: lib components for the libXrandr package.
Group: Libraries

%description lib
lib components for the libXrandr package.


%prep
%setup -q -n libXrandr-1.5.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xrandr.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
